server:
  port: 8080
logging:
  level:
    root: info

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:h2:mem:test
#    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      max-lifetime: 1800000
      pool-name: HikariCP
      read-only: false
      connection-test-query: SELECT 1


developer:
  kakao:
    host: https://dapi.kakao.com
    authorization: KakaoAK 7ed09a50472b6f82b7b9ad8e7ebed1ab
  naver:
    host: https://openapi.naver.com
    client-id: G0JVYckW97wrf7MxbP3r
    client-secret: NdSG2FJnTY
